### ISSUE TITLE
AC97 to Reactos..

### ISSUE THREAD

**Issue by blackcrack** [Zero3K/AC97#1]
Hi @Zero3K ,

a big fad thank you to you :)
finally have Reactos the actually intel-AC97 included (well done)
(i hope it is that )
take a look : 
https://www.catalog.update.microsoft.com/Search.aspx?q=82801AA%20AC%2797%20
I did not want to post this in Reactos, but only you, that not one or the other shoots it ..

best regards
Blacky

**Comment by blackcrack** [comment]
private posting ..

**Comment by Zero3K** [comment]
This is just the source code of it, it hasn't been included. I hope that it eventually is and can also be improved upon/used so audio works in ReactOS.

**Comment by blackcrack** [comment]
oh ja, i hope it too :)

you could maybe also announce the drivers from MS Download Catalog
because they works on 32Bit WinNT systems and is imho the orginal hardwaredrivers where be emulated innotek in this time by building up VBox, This drivers works on WinXP and Reactos..
but because the one or the other makes a bad reputation about me, do they not use the 
well working original intel drivers .. in other hand, i know, the trademark or regesried under a other Licence ... but this is  imbecility.. this hardware is older than 10 years ... why should Reactos not use the orgrinal and last version of this drivers ....

have a nice day 
best regards
Blacky

**Comment by Zero3K** [comment]
They would rather use an open-source version of it (which this supposedly is). I tried using the driver it made when I compiled it but it didn't work. It was probably because the target OS was Windows 7, not Windows Server 2003.

**Comment by blackcrack** [comment]
i guess too.. win7/8  there for i have search this drivers for this emulated hardware which works.. but, i guess, there must be a bit tinkering need from programmer like u to be this works in reactos ;) .. \*fingercross*

thy for this conversation and info swapping :)))

best regards
Blacky

**Comment by Zero3K** [comment]
I am not a programmer. Just a user who made a clone of the source code for the audio driver.

**Comment by blackcrack** [comment]
oh well, like me, have more as 20 Years Computer behind me..
a bit php, batch/cmd and sh in linux.. if you want a bit swapping/cluttering around,
http://blackysgate.de/files have fun :)
